name: "action-cosmos"
description: "Send Messages to Messengers"
author: "action-cosmos"

inputs:
  app_token:
    description: "Personal token for call"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  color: "orange"
  icon: "send"